App_usage_analytics_data

In [1]:
import sys
!python.exe -m pip install --upgrade pip

Requirement already satisfied: pip in .\.venv\Lib\site-packages (26.1.1)

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

Loading Data Set

In [6]:
df = pd.read_csv("C:/Users/hp/OneDrive/Desktop/Project github/app_usage_analytics_data.csv")

Data Cleaning

In [7]:
df.head(10)

,User_ID,Session_ID,App_Version,Device_Type,OS,Country,City,Session_Start,Session_End,Session_Duration_Min,Screens_Viewed,Clicks,Active_Time_Min,Idle_Time_Min,Crash_Flag,In_App_Purchase,Purchase_Amount,Ad_Clicks,Notifications_Opened,Retention_Flag
0,293644,S0,2.0,Mobile,iOS,Canada,Mumbai,2022-03-29 03:52:00,2022-03-29 04:17:00,25,21,120,18,1,0,0,0.00,8,10,0
1,441886,S1,2.0,Tablet,iOS,UK,Chennai,2022-10-08 23:32:00,2022-10-09 00:33:00,61,7,176,26,50,0,0,0.00,8,7,1
2,500715,S2,2.1,Mobile,iOS,USA,Delhi,2024-01-23 08:54:00,2024-01-23 09:21:00,27,3,137,19,17,0,1,2763.19,13,4,0
3,800847,S3,3.0,Mobile,iOS,India,Mumbai,2024-05-27 05:41:00,2024-05-27 07:14:00,93,14,181,75,15,0,1,4735.41,15,9,1
4,469086,S4,1.1,Tablet,iOS,India,Delhi,2022-11-08 23:07:00,2022-11-08 23:40:00,33,50,114,16,19,0,0,0.00,1,1,0
5,41843,S5,3.0,Tablet,iOS,India,Mumbai,2022-09-15 10:29:00,2022-09-15 12:15:00,106,18,168,36,69,0,1,462.50,8,8,0
6,232916,S6,1.1,Mobile,Android,USA,Chennai,2023-09-06 22:48:00,2023-09-06 22:59:00,11,16,42,7,6,1,1,4067.90,20,5,0
7,629780,S7,1.1,Mobile,iOS,UK,Bhopal,2023-09-25 16:16:00,2023-09-25 16:22:00,6,49,151,6,1,0,1,1511.42,17,9,1
8,532104,S8,1.1,Tablet,iOS,Canada,Delhi,2024-04-23 11:38:00,2024-04-23 12:58:00,80,11,66,26,23,1,1,4143.49,15,7,1
9,338782,S9,1.0,Mobile,Android,India,Delhi,2023-09-11 13:29:00,2023-09-11 14:33:00,64,13,60,21,36,0,1,3588.35,19,1,0

In [8]:
df.tail()

,User_ID,Session_ID,App_Version,Device_Type,OS,Country,City,Session_Start,Session_End,Session_Duration_Min,Screens_Viewed,Clicks,Active_Time_Min,Idle_Time_Min,Crash_Flag,In_App_Purchase,Purchase_Amount,Ad_Clicks,Notifications_Opened,Retention_Flag
89995,957770,S89995,2.1,Mobile,Android,UK,Mumbai,2022-07-22 04:33:00,2022-07-22 05:27:00,54,35,87,46,13,1,0,0.00,1,8,0
89996,367835,S89996,1.0,Tablet,iOS,USA,Delhi,2022-04-15 07:05:00,2022-04-15 07:51:00,46,1,53,32,8,1,0,0.00,2,10,1
89997,906580,S89997,2.1,Tablet,iOS,UK,Delhi,2022-03-10 12:26:00,2022-03-10 13:59:00,93,19,143,40,61,1,1,1764.06,12,7,0
89998,440063,S89998,2.0,Tablet,iOS,UK,Chennai,2024-07-04 15:36:00,2024-07-04 16:01:00,25,22,167,16,18,0,0,0.00,1,9,0
89999,312988,S89999,3.0,Mobile,Android,USA,Delhi,2023-05-25 04:21:00,2023-05-25 05:23:00,62,46,33,59,24,0,1,3245.36,1,3,1

In [9]:
df.columns

Index(['User_ID', 'Session_ID', 'App_Version', 'Device_Type', 'OS', 'Country',
       'City', 'Session_Start', 'Session_End', 'Session_Duration_Min',
       'Screens_Viewed', 'Clicks', 'Active_Time_Min', 'Idle_Time_Min',
       'Crash_Flag', 'In_App_Purchase', 'Purchase_Amount', 'Ad_Clicks',
       'Notifications_Opened', 'Retention_Flag'],
      dtype='str')

In [10]:
df.shape

(90000, 20)

Exploratory Data Analysis

In [11]:
df.describe()

,User_ID,App_Version,Session_Duration_Min,Screens_Viewed,Clicks,Active_Time_Min,Idle_Time_Min,Crash_Flag,In_App_Purchase,Purchase_Amount,Ad_Clicks,Notifications_Opened,Retention_Flag
count,90000.000000,90000.000000,90000.000000,90000.000000,90000.000000,90000.000000,90000.000000,90000.000000,90000.000000,90000.000000,90000.000000,90000.000000,90000.000000
mean,499526.244033,1.840359,60.398056,25.401578,100.692533,30.781156,30.203833,0.498611,0.502933,1252.940297,9.997489,5.002344,0.497600
std,288752.847637,0.732722,34.701268,14.430330,57.652385,26.666042,26.742652,0.500001,0.499994,1609.126672,6.053087,3.162075,0.499997
min,1002.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,248492.750000,1.100000,30.000000,13.000000,51.000000,9.000000,8.000000,0.000000,0.000000,0.000000,5.000000,2.000000,0.000000
50%,499505.500000,2.000000,60.000000,25.000000,100.000000,23.000000,23.000000,0.000000,1.000000,36.110000,10.000000,5.000000,0.000000
75%,750260.000000,2.100000,90.000000,38.000000,151.000000,47.000000,46.000000,1.000000,1.000000,2493.475000,15.000000,8.000000,1.000000
max,999984.000000,3.000000,120.000000,50.000000,200.000000,120.000000,120.000000,1.000000,1.000000,4999.990000,20.000000,10.000000,1.000000

In [12]:
df.isnull().sum()

User_ID                 0
Session_ID              0
App_Version             0
Device_Type             0
OS                      0
Country                 0
City                    0
Session_Start           0
Session_End             0
Session_Duration_Min    0
Screens_Viewed          0
Clicks                  0
Active_Time_Min         0
Idle_Time_Min           0
Crash_Flag              0
In_App_Purchase         0
Purchase_Amount         0
Ad_Clicks               0
Notifications_Opened    0
Retention_Flag          0
dtype: int64

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 90000 entries, 0 to 89999
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   User_ID               90000 non-null  int64
 1   Session_ID            90000 non-null  str
 2   App_Version           90000 non-null  float64
 3   Device_Type           90000 non-null  str
 4   OS                    90000 non-null  str
 5   Country               90000 non-null  str
 6   City                  90000 non-null  str
 7   Session_Start         90000 non-null  str
 8   Session_End           90000 non-null  str
 9   Session_Duration_Min  90000 non-null  int64
 10  Screens_Viewed        90000 non-null  int64
 11  Clicks                90000 non-null  int64
 12  Active_Time_Min       90000 non-null  int64
 13  Idle_Time_Min         90000 non-null  int64
 14  Crash_Flag            90000 non-null  int64
 15  In_App_Purchase       90000 non-null  int64
 16  Purchase_Amount       90000 non-null  float64
 17  Ad_Clicks             90000 non-null  int64
 18  Notifications_Opened  90000 non-null  int64
 19  Retention_Flag        90000 non-null  int64
dtypes: float64(2), int64(11), str(7)
memory usage: 19.4 MB

In [14]:
df.drop_duplicates()

,User_ID,Session_ID,App_Version,Device_Type,OS,Country,City,Session_Start,Session_End,Session_Duration_Min,Screens_Viewed,Clicks,Active_Time_Min,Idle_Time_Min,Crash_Flag,In_App_Purchase,Purchase_Amount,Ad_Clicks,Notifications_Opened,Retention_Flag
0,293644,S0,2.0,Mobile,iOS,Canada,Mumbai,2022-03-29 03:52:00,2022-03-29 04:17:00,25,21,120,18,1,0,0,0.00,8,10,0
1,441886,S1,2.0,Tablet,iOS,UK,Chennai,2022-10-08 23:32:00,2022-10-09 00:33:00,61,7,176,26,50,0,0,0.00,8,7,1
2,500715,S2,2.1,Mobile,iOS,USA,Delhi,2024-01-23 08:54:00,2024-01-23 09:21:00,27,3,137,19,17,0,1,2763.19,13,4,0
3,800847,S3,3.0,Mobile,iOS,India,Mumbai,2024-05-27 05:41:00,2024-05-27 07:14:00,93,14,181,75,15,0,1,4735.41,15,9,1
4,469086,S4,1.1,Tablet,iOS,India,Delhi,2022-11-08 23:07:00,2022-11-08 23:40:00,33,50,114,16,19,0,0,0.00,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89995,957770,S89995,2.1,Mobile,Android,UK,Mumbai,2022-07-22 04:33:00,2022-07-22 05:27:00,54,35,87,46,13,1,0,0.00,1,8,0
89996,367835,S89996,1.0,Tablet,iOS,USA,Delhi,2022-04-15 07:05:00,2022-04-15 07:51:00,46,1,53,32,8,1,0,0.00,2,10,1
89997,906580,S89997,2.1,Tablet,iOS,UK,Delhi,2022-03-10 12:26:00,2022-03-10 13:59:00,93,19,143,40,61,1,1,1764.06,12,7,0
89998,440063,S89998,2.0,Tablet,iOS,UK,Chennai,2024-07-04 15:36:00,2024-07-04 16:01:00,25,22,167,16,18,0,0,0.00,1,9,0
89999,312988,S89999,3.0,Mobile,Android,USA,Delhi,2023-05-25 04:21:00,2023-05-25 05:23:00,62,46,33,59,24,0,1,3245.36,1,3,1

 VISUALIZATION DASHBOARD

In [16]:
import plotly.express as px

In [15]:
total_users = df['User_ID'].nunique()
total_sessions = df['Session_ID'].nunique()
avg_duration = df['Session_Duration_Min'].mean()
total_revenue = df['Purchase_Amount'].sum()
crash_rate = df['Crash_Flag'].mean() * 100
retention_rate = df['Retention_Flag'].mean() * 100

User Engagement Dashboard

Session Duration Distribution

In [17]:
px.histogram(df, x='Session_Duration_Min')

Active vs Idle Time

In [18]:
px.scatter(
    df,
    x='Active_Time_Min',
    y='Idle_Time_Min',
    color='Device_Type'
)

Screens Viewed by Device

In [19]:
px.box(df, x='Device_Type', y='Screens_Viewed')

Revenue Dashboard

Revenue by Country

In [20]:
country_rev = df.groupby('Country')['Purchase_Amount'].sum().reset_index()

px.bar(country_rev,
       x='Country',
       y='Purchase_Amount')

In-App Purchase Conversion

In [21]:
purchase_rate = df['In_App_Purchase'].mean() * 100

Revenue by Device Type

In [22]:
px.pie(df,
       names='Device_Type',
       values='Purchase_Amount')

Crash Analytics Dashboard

Crash Rate by App Version

In [23]:
crash_version = df.groupby('App_Version')['Crash_Flag'].mean().reset_index()

px.line(crash_version,
        x='App_Version',
        y='Crash_Flag')

Crash by OS

In [24]:
px.bar(df.groupby('OS')['Crash_Flag'].mean().reset_index(),
       x='OS',
       y='Crash_Flag')

Retention Analytics

Retention by Country

In [25]:
ret = df.groupby('Country')['Retention_Flag'].mean().reset_index()

px.bar(ret,
       x='Country',
       y='Retention_Flag')

Retention vs Session Duration

In [26]:
px.scatter(
    df,
    x='Session_Duration_Min',
    y='Retention_Flag'
)

Advertisement Analytics

Ad Clicks by Country

In [27]:
ads = df.groupby('Country')['Ad_Clicks'].sum().reset_index()

px.bar(ads,
       x='Country',
       y='Ad_Clicks')

Notifications Opened vs Purchases

In [28]:
px.scatter(
    df,
    x='Notifications_Opened',
    y='Purchase_Amount'
)

Device Analytics

In [29]:
px.pie(df, names='Device_Type')

OS Distribution

In [31]:
px.bar(df['OS'].value_counts())